# Generated by Django 5.0.3 on 2024-12-07 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgriculturalTourBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('preferred_date', models.DateField()),
                ('group_size', models.PositiveIntegerField()),
                ('tour_type', models.CharField(choices=[('farm-tour', 'Farm Tour'), ('harvest-experience', 'Harvest Experience'), ('workshop', 'Agricultural Workshop'), ('food-tasting', 'Food Tasting')], max_length=50)),
                ('special_requirements', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
