# Generated by Django 5.0.3 on 2025-02-05 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=100)),
                ('crop_image', models.ImageField(upload_to='crop_images/')),
                ('quantity', models.PositiveIntegerField()),
                ('additional_details', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
